radar_pcl_filter_node:
  ros__parameters:
    drone_threshold: 1.0
    leaf_size: 0.1
    cluster_crop_radius: 325.0
    ground_threshold: -4.0
    line_model_inlier_threshold: 10.0
    radar_elevation_fov: 60.0
    radar_azimuth_fov: 140.0
    line_or_point_follow: "line"
    add_crop_downsample_rate: 5
    plus_or_minus_yaw: -1
    tracking_update_euclid_dist: 5.0
    downsample_rate: 999999999
    
offboard_control:
  ros__parameters:
    powerline_following_distance: 5.0
    powerline_following_speed: 3.5
